
-- 

COMMENT ON TABLE  orig_osm.ego_deu_loads_osm IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "area_ha",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.ego_deu_loads_osm'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_line IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "osm_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "access",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housename",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housnumber",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:interpolation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "admin_level",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aerialway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aeroway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "amenity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "area",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "barrier",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bicycle",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "brand",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bridge",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "boundary",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "building",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "construction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "covered",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "culvert",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "cutting",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "denomination",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "disused",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "embankment",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "foot",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "generator:source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "harbour",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "highway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "historic",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "horse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "intermittent",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "junction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "landuse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "layer",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "leisure",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lock",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "man_made",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "military",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "motorcar",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "name",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "natural",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "office",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "oneway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "operator",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "place",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "population",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power_source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "public_transport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "railway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "ref",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "religion",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "route",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "service",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "shop",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "sport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "surface",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "toll",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tourism",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tower:type",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tracktype",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tunnel",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "water",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "waterway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wetland",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "witdth",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wood",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "z_order",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "way_area",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_line'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_nodes IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "lat",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lon",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_nodes'::regclass)::json;

--

-- 

COMMENT ON TABLE  orig_osm.osm_deu_point IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "osm_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "access",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housename",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housnumber",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:interpolation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "admin_level",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aerialway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aeroway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "amenity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "area",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "barrier",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bicycle",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "brand",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bridge",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "boundary",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "building",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "capital",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "construction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "covered",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "culvert",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "cutting",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "denomination",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "disused",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "ele",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "embankment",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "foot",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "generator:source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "harbour",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "highway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "historic",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "horse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "intermittent",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "junction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "landuse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "layer",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "leisure",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lock",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "man_made",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "military",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "motorcar",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "name",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "natural",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "office",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "oneway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "operator",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "place",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "poi",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "population",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power_source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "public_transport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "railway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "ref",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "religion",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "route",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "service",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "shop",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "sport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "surface",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "toll",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tourism",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tower:type",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tunnel",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "water",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "waterway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wetland",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "witdth",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wood",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "z_order",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_point'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_polygon IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "osm_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "access",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housename",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housnumber",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:interpolation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "admin_level",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aerialway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aeroway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "amenity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "area",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "barrier",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bicycle",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "brand",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bridge",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "boundary",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "building",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "construction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "covered",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "culvert",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "cutting",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "denomination",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "disused",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "embankment",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "foot",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "generator:source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "harbour",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "highway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "historic",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "horse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "intermittent",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "junction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "landuse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "layer",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "leisure",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lock",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "man_made",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "military",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "motorcar",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "name",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "natural",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "office",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "oneway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "operator",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "place",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "population",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power_source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "public_transport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "railway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "ref",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "religion",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "route",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "service",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "shop",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "sport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "surface",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "toll",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tourism",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tower:type",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tracktype",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tunnel",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "water",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "waterway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wetland",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "witdth",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wood",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "z_order",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "way_area",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_polygon'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_polygon_urban_old IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "osm_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "name",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "sector",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_polygon_urban_old'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_rels IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "way_off",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "rel_off",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "parts",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "members",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "pending",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_rels'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_roads IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "osm_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "access",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housename",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:housnumber",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "addr:interpolation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "admin_level",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aerialway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "aeroway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "amenity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "area",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "barrier",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bicycle",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "brand",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bridge",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "boundary",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "building",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "construction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "covered",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "culvert",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "cutting",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "denomination",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "disused",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "embankment",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "foot",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "generator:source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "harbour",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "highway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "historic",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "horse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "intermittent",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "junction",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "landuse",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "layer",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "leisure",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lock",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "man_made",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "military",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "motorcar",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "name",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "natural",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "office",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "oneway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "operator",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "place",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "population",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "power_source",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "public_transport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "railway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "ref",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "religion",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "route",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "service",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "shop",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "sport",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "surface",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "toll",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tourism",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tower:type",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tracktype",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tunnel",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "water",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "waterway",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wetland",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "witdth",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wood",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "z_order",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "way_area",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_roads'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_osm.osm_deu_ways IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "nodes",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "pending",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_osm.osm_deu_ways'::regclass)::json;

--


