
-- 

COMMENT ON TABLE  orig_vg250.vg250_1_sta IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ade",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gf",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bsg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sdv_rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_l",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_r",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_k",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v1",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v2",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_g",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "fk_s3",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" },      
                   {"Name": "wsk",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_1_sta'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_2_lan IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ade",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gf",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bsg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sdv_rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_l",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_r",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_k",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v1",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v2",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_g",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "fk_s3",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" },      
                   {"Name": "wsk",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_2_lan'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_3_rbz IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ade",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gf",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bsg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sdv_rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_l",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_r",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_k",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v1",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v2",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_g",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "fk_s3",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" },      
                   {"Name": "wsk",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_3_rbz'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_4_krs IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ade",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gf",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bsg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sdv_rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_l",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_r",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_k",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v1",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v2",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_g",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "fk_s3",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" },      
                   {"Name": "wsk",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_4_krs'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_5_vwg IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ade",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gf",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bsg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sdv_rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_l",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_r",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_k",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v1",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v2",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_g",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "fk_s3",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" },      
                   {"Name": "wsk",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_5_vwg'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_6_gem IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ade",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gf",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bsg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sdv_rs",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_l",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_r",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_k",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v1",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_v2",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "sn_g",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "fk_s3",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" },      
                   {"Name": "wsk",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_6_gem'::regclass)::json;

--



-- 

COMMENT ON TABLE  orig_vg250.vg250_6_gem_clean IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nuts",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "rs_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ags_0",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "area_ha",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "count_ring",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "path",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "is_ring",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_6_gem_clean'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_li IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "agz",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "rdg",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "gm5",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_li'::regclass)::json;

--


-- 

COMMENT ON TABLE  orig_vg250.vg250_pk IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "rs",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "ags",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gen",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "ibz",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "bem",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "nbd",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "lon_dez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "lat_dez",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "lon_gms",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "lat__gms",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "debkg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "10.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_vg250.vg250_pk'::regclass)::json;

--

