-- 

COMMENT ON TABLE  orig_geo_opsd.opsd_hourly_timeseries IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "timestamp",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_at",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_ba",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_be",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_bg",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_ch",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_cs",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_cy",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_cz",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_de",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_dk",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_dkw",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_ee",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_es",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_fi",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_fr",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_gb",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_gr",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_hr",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_hu",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_ie",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_is",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_it",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_lt",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_lu",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_lv",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_me",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_mk",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_ni",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_nl",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_no",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_pl",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_pt",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_ro",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_rs",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_se",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_si",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_sk",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "load_uaw",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_de_capacity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_de_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_de_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_de_profile",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_de50hertz_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_de50hertz_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_deamprion_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_deamprion_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_detennet_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_detennet_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_detransnetbw_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "solar_detransnetbw_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_de_capacity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_de_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_de_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_de_profile",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_de50hertz_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_de50hertz_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_deamprion_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_deamprion_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_detennet_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_detennet_generation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_detransnetbw_forecast",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "wind_detransnetbw_generation",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "05.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_geo_opsd.opsd_hourly_timeseries'::regclass)::json;

--

-- 

COMMENT ON TABLE  orig_geo_opsd.opsd_power_plants_germany IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "gid",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "bnetza_id",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "company",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "name",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "postcode",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "city",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "street",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "state",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "block",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "commissioned_original",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "commissioned",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "retrofit",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "shutdown",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "status",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "fuel",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "technology",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "type",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "eeg",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "chp",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "capacity",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "capacity_uba",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "chp_capacity_uba",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "efficiency_data",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "efficiency_estimate",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "network_node",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "voltage",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "network_operator",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "name_uba",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "lat",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "lon",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "comment",
                    "Description": "...",
                    "Unit": "" },                             
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "05.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_geo_opsd.opsd_power_plants_germany'::regclass)::json;

--

-- 

COMMENT ON TABLE  orig_geo_opsd.renewable_power_plants_germany IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "start_up_date",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "electrical_capacity",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "generation_type",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "generation_subtype",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "thermal_capacity",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "city",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "postcode",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "address",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lon",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "lat",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "gps_accuracy",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "validation",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "notification_reason",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "eeg_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tso",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "tso_eic",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "dso_id",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "dso",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "voltage_level",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "network_node",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "power_plant_id",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "source",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "comment",
                    "Description": "...",
                    "Unit": "" },                           
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "05.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_geo_opsd.renewable_power_plants_germany'::regclass)::json;

--

-- 

COMMENT ON TABLE  orig_geo_opsd.renewable_power_plants_germany_hv_solar_roof IS
'{
"Name": "...",
"Source": [{
                  "Name": "...",
                  "URL":  "..." }],
"Reference date": "...",
"Date of collection": "...",
"Original file": "...",
"Spatial resolution": ["Germany"],
"Description": ["..."],
"Column": [
                   {"Name": "id",
                    "Description": "...",
                    "Unit": "" },  
                   {"Name": "electrical_capacity",
                    "Description": "...",
                    "Unit": "" },     
                   {"Name": "generation_type",
                    "Description": "...",
                    "Unit": "" }, 
                   {"Name": "generation_subtype",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "voltage_level",
                    "Description": "...",
                    "Unit": "" },
                   {"Name": "subst_id",
                    "Description": "...",
                    "Unit": "" },                          
                   {"Name": "geom",
                    "Description": "...",
                    "Unit": "" }],
"Changes":[
                   {"Name": "Mario Kropshofer",
                    "Mail": "mario.kropshofer2@stud.fh-flensburg.de",
                    "Date":  "05.10.2016",
                    "Comment": "..." }
                  ],
"ToDo": ["Please complete"],
"Licence": ["..."],
"Instructions for proper use": ["..."]
}';


SELECT obj_description('orig_geo_opsd.renewable_power_plants_germany_hv_solar_roof'::regclass)::json;

--


